BEGIN;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  git_username VARCHAR (255) NOT NULL,
  git_profile_url VARCHAR (2083) NOT NULL,
  git_photo_url VARCHAR (2083) NOT NULL,
  elo_ranking INTEGER DEFAULT 1500
);
DROP TABLE IF EXISTS ratings CASCADE;

CREATE TABLE ratings (
  rating_id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES USERS(user_id),
  winner BOOLEAN NOT NULL,
  opponent_id INTEGER NOT NULL REFERENCES USERS(user_id),
  opponent_elo INTEGER DEFAULT 1500
);
COMMIT;
